---
# tasks file for php
- name: package install
  ignore_errors: yes
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++
    #- systemd
    - httpd
    - httpd-devel
    - nginx
    #- nginx-devel
    - mysql
    - mysql-server
    #- mysql-compat
    - mysql-devel
    - libxml2-devel
    - curl-devel
    - libjpeg
    - libpng
    - libjpeg-devel
    - libpng-devel
    - gd
    - gd-devel
    - libmcrypt
    - libmcrypt-devel
    - unixODBC
    - unixODBC-devel
    - postgresql
    - postgresql-devel
    - sqlite
    - sqlite-devel

#http://jp2.php.net/get/php-5.6.10.tar.gz/from/this/mirror -O php.tar.gz
- name: get php file
  get_url: url="http://jp2.php.net/get/{{ php_version }}.tar.gz/from/this/mirror" dest=/tmp/php.tar.gz
